// Auto-generated — 2026-06-04 01:24:50
// 46 files from photos folder
window.PHOTO_DATA = [
  { type: "image", src: "photos/5.20.1.jpg", title: "5.20.1", subtitle: "", category: "other", tagText: "照片" },
  { type: "image", src: "photos/5.20.10.jpg", title: "5.20.10", subtitle: "", category: "other", tagText: "照片" },
  { type: "image", src: "photos/5.20.11.jpg", title: "5.20.11", subtitle: "", category: "other", tagText: "照片" },
  { type: "image", src: "photos/5.20.12.jpg", title: "5.20.12", subtitle: "", category: "other", tagText: "照片" },
  { type: "image", src: "photos/5.20.13.jpg", title: "5.20.13", subtitle: "", category: "other", tagText: "照片" },
  { type: "image", src: "photos/5.20.14.jpg", title: "5.20.14", subtitle: "", category: "other", tagText: "照片" },
  { type: "image", src: "photos/5.20.2.jpg", title: "5.20.2", subtitle: "", category: "other", tagText: "照片" },
  { type: "image", src: "photos/5.20.3.jpg", title: "5.20.3", subtitle: "", category: "other", tagText: "照片" },
  { type: "image", src: "photos/5.20.4.jpg", title: "5.20.4", subtitle: "", category: "other", tagText: "照片" },
  { type: "image", src: "photos/5.20.5.jpg", title: "5.20.5", subtitle: "", category: "other", tagText: "照片" },
  { type: "image", src: "photos/5.20.6.jpg", title: "5.20.6", subtitle: "", category: "other", tagText: "照片" },
  { type: "image", src: "photos/5.20.7.jpg", title: "5.20.7", subtitle: "", category: "other", tagText: "照片" },
  { type: "image", src: "photos/5.20.8.jpg", title: "5.20.8", subtitle: "", category: "other", tagText: "照片" },
  { type: "image", src: "photos/5.20.9.jpg", title: "5.20.9", subtitle: "", category: "other", tagText: "照片" },
  { type: "video", src: "photos/5.20.mp4", title: "5.20", subtitle: "", category: "other", tagText: "视频", duration: "00:00:14" },
  { type: "image", src: "photos/ScreenShot_2026-03-17_212021_249.png", title: "ScreenShot_2026-03-17_212021_249", subtitle: "", category: "other", tagText: "照片" },
  { type: "image", src: "photos/飞儿1.jpg", title: "飞儿1", subtitle: "", category: "other", tagText: "照片" },
  { type: "image", src: "photos/飞儿10.jpg", title: "飞儿10", subtitle: "", category: "other", tagText: "照片" },
  { type: "image", src: "photos/飞儿11.jpg", title: "飞儿11", subtitle: "", category: "other", tagText: "照片" },
  { type: "image", src: "photos/飞儿12.jpg", title: "飞儿12", subtitle: "", category: "other", tagText: "照片" },
  { type: "image", src: "photos/飞儿13.jpg", title: "飞儿13", subtitle: "", category: "other", tagText: "照片" },
  { type: "image", src: "photos/飞儿14.jpg", title: "飞儿14", subtitle: "", category: "other", tagText: "照片" },
  { type: "image", src: "photos/飞儿15.jpg", title: "飞儿15", subtitle: "", category: "other", tagText: "照片" },
  { type: "image", src: "photos/飞儿16.jpg", title: "飞儿16", subtitle: "", category: "other", tagText: "照片" },
  { type: "image", src: "photos/飞儿17.jpg", title: "飞儿17", subtitle: "", category: "other", tagText: "照片" },
  { type: "image", src: "photos/飞儿18.jpg", title: "飞儿18", subtitle: "", category: "other", tagText: "照片" },
  { type: "image", src: "photos/飞儿19.jpg", title: "飞儿19", subtitle: "", category: "other", tagText: "照片" },
  { type: "image", src: "photos/飞儿2.jpg", title: "飞儿2", subtitle: "", category: "other", tagText: "照片" },
  { type: "video", src: "photos/飞儿2.mp4", title: "飞儿2", subtitle: "", category: "other", tagText: "视频", duration: "00:00:31" },
  { type: "image", src: "photos/飞儿20.jpg", title: "飞儿20", subtitle: "", category: "other", tagText: "照片" },
  { type: "image", src: "photos/飞儿21.jpg", title: "飞儿21", subtitle: "", category: "other", tagText: "照片" },
  { type: "image", src: "photos/飞儿22.jpg", title: "飞儿22", subtitle: "", category: "other", tagText: "照片" },
  { type: "image", src: "photos/飞儿23.jpg", title: "飞儿23", subtitle: "", category: "other", tagText: "照片" },
  { type: "image", src: "photos/飞儿24.jpg", title: "飞儿24", subtitle: "", category: "other", tagText: "照片" },
  { type: "image", src: "photos/飞儿3.jpg", title: "飞儿3", subtitle: "", category: "other", tagText: "照片" },
  { type: "image", src: "photos/飞儿4.jpg", title: "飞儿4", subtitle: "", category: "other", tagText: "照片" },
  { type: "image", src: "photos/飞儿5.jpg", title: "飞儿5", subtitle: "", category: "other", tagText: "照片" },
  { type: "image", src: "photos/飞儿6.jpg", title: "飞儿6", subtitle: "", category: "other", tagText: "照片" },
  { type: "image", src: "photos/飞儿7.jpg", title: "飞儿7", subtitle: "", category: "other", tagText: "照片" },
  { type: "image", src: "photos/飞儿8.jpg", title: "飞儿8", subtitle: "", category: "other", tagText: "照片" },
  { type: "image", src: "photos/飞儿9.jpg", title: "飞儿9", subtitle: "", category: "other", tagText: "照片" },
  { type: "video", src: "photos/飞儿视频3.mp4", title: "飞儿视频3", subtitle: "", category: "other", tagText: "视频", duration: "00:00:18" },
  { type: "video", src: "photos/飞儿视频4.mp4", title: "飞儿视频4", subtitle: "", category: "other", tagText: "视频", duration: "00:00:21" },
  { type: "video", src: "photos/飞儿视频5.mp4", title: "飞儿视频5", subtitle: "", category: "other", tagText: "视频", duration: "00:00:16" },
  { type: "video", src: "photos/飞儿视频6.mp4", title: "飞儿视频6", subtitle: "", category: "other", tagText: "视频", duration: "00:00:06" },
  { type: "video", src: "photos/视频1.mp4", title: "视频1", subtitle: "", category: "other", tagText: "视频", duration: "00:00:18" }
];